### ISSUE TITLE
Set workflowStatus to pending

### ISSUE THREAD

**Issue by starsplatter** [cul-it/order-import-poc#23]
The orders are currently set to open but acquisitions would like to set them to pending.

**Comment by cappadona** [comment]
I'll take this one.

**Comment by cappadona** [comment]
@starsplatter Are you familiar with [`mod-orders` business logic concerning PO workflow status](https://github.com/folio-org/mod-orders#purchase-order-logic)? I'm not, but based on what I'm finding, it appears that the PO `workflowStatus` must be `Open` when  making changes to Inventory.

Does Acquisitions want the status to be set back to `Pending` after those Inventory changes are made? Is that a legitimate workflow? Perhaps we should loop one/all of them in?

**Comment by starsplatter** [comment]
This was their request, I'll check with them about whether they understand the implication.

**Comment by starsplatter** [comment]
Hi- we don't want to make inventory changes until orders are approved and set to open, at which point FOLIO makes the inventory pieces.

**Comment by cappadona** [comment]
Morning. We're talking about inventory changes beyond [initial creation](https://github.com/cul-it/order-import-poc/blob/main/src/main/java/org/olf/folio/order/OrderImport.java#L203-L237) of the `instance`, `holding`, and `item` (where applicable)?

My limited understanding is that the PO must have a status of `open` , otherwise creation of inventory bits are restricted and seen as a violation.

If we want POs submitted through this app to have a status of `pending` as the final result, my understanding is that we would temporarily need to:
1. set the status to `open`
2. create the inventory bits
3. go back and change the status of the PO to `pending` at the very end

I haven't tested this and I also have no clue whether it's a legitimate PO workflow

**Comment by starsplatter** [comment]
Response from the group so far based on these complications is to let the app stick with setting them to open and they'll run a report to find them.

**Comment by cappadona** [comment]
Thanks. By report do you mean using a combination of filters in the Orders app, along with [Created by](https://cornell-training.folio.ebsco.com/orders?metadata.createdByUserId=8720f87c-1918-4658-b081-04f165689627)?

**Comment by fereira** [comment]
Using "Created By" and "open" would filter any POs that might need attention.

**Comment by starsplatter** [comment]
I forgot that we have a special user for this, that will be a great way to do this. Thank you!!!

**Comment by starsplatter** [comment]
I got confirmation from the owner of this process that we don't need to do this. Thank you both for your help!
