### ISSUE TITLE
Map notes from MARC

### ISSUE THREAD

**Issue by starsplatter** [cul-it/order-import-poc#29]
Please map:

980$z – internal note
981$n – receiving note

## This is a follow up to the discussion during review of #18:

We'll need to run this by @starsplatter  and LTS Acquisitions, but I don't think we want to use the generic FOLIO Notes for either of the following notes mapped from the MARC (see #9) and meant for a PO Line:
* Internal Note (`980$z`)
* Receiving Note (`981$n`)

The Receiving Note is straightforward. It's a legitimate field defined in the schema for PO Line details:
https://github.com/folio-org/acq-models/blob/60282f116ab3ccb86016a84d9bef99b1dc8ecc4f/mod-orders-storage/schemas/details.json#L6-L9

The Internal Note is more interesting, and as far as I can tell is not a _real_ field, and instead is relabeling/repurposing the PO Line `description`:
https://github.com/folio-org/ui-orders/blob/0d918c5dcbe48019d5eca432c4958858c6cd5ef3/src/components/POLine/Item/ItemView.js#L113-L114

> Review [UIOR-295](https://issues.folio.org/browse/UIOR-285) for more details and background

_Originally posted by @cappadona in https://github.com/cul-it/order-import-poc/pull/18#discussion_r606373915_

**Comment by fereira** [comment]
In order to test this, the app_order-import account requires the following permission: notes.item.get (notes.item.post is already there). 

The contents of 981$n fields in the marc files look something like this:

**See: https://www.printedmatter.org/catalog/57182/ Pickup location: Africana LibraryREQ:met228@cornell.edu**

Notice the REQ delimiter followed by the requestor email address.  Should I strip that off?

I'm still not sure what, if anything, should be done with the "Internal Note" field.

**Comment by cappadona** [comment]
Hi @fereira.

We shouldn't need [`notes.item.post`, `notes.item.get`](https://github.com/folio-org/mod-notes/blob/4a612c085841dcf76f89c7abaef1e54e5da5c544/descriptors/ModuleDescriptor-template.json#L125-L134), or any `notes.` permission  included in the permission set for this app since we've decided that we will not be using `mod-notes` for either the Internal or Receiving note.

As stated in the issue summary, the Internal Note (`981$n`) should be put in the `description` of the applicable PO Line when POSTing the composite order.
> The Internal Note is more interesting, and as far as I can tell is not a real field, and instead is relabeling/repurposing the PO Line description:
https://github.com/folio-org/ui-orders/blob/0d918c5dcbe48019d5eca432c4958858c6cd5ef3/src/components/POLine/Item/ItemView.js#L113-L114
>
> Review [UIOR-295](https://issues.folio.org/browse/UIOR-285) for more details and background

Jenn's on the road so I say don't strip anything from the `981n` for now. We can always tweak it next week if needed. Thanks.

**Comment by fereira** [comment]
No wonder I'm confused.  In comments above it indicate the 981$n field/sub-field is for the Receiving Note, not the internal note.  Previous comments also don't specifically say that we won't be using mod-notes, or that the internal note *should* be used for the description.  I'll wait for Jenn to come back to let me know what is wanted.

**Comment by cappadona** [comment]
Sorry...typo on my part in that last comment, John. I've corrected it above.

**Comment by fereira** [comment]
OK, here's the kind of content I'm getting from the 980$z field:

POOF;http://poof2.library.cornell.edu/orders/32553;Cornell

Only 3 of the marc files have that field populated and in every case it's a poof link

**Comment by cappadona** [comment]
Thanks. No surprises there, that's exactly what the [POOF template](https://github.com/cul-it/poof2/blob/2e837b13e9823582f40a73d1191125290c597a69/tmpltfiles/cts.xml#L9) specifies.

**Comment by starsplatter** [comment]
Hi @fereira -
So I think this is still what we want to have happen:

* Internal Note will come from the MARC 980$z and be imported as the PO Line `description` (this is called internal  note in the UI and I think that's what was causing confusion)
* Receiving Note will come from the MARC 981$n and be imported as the PO line `receivingNote`

I don't think we  need to strip anything from these. The internal note is  just a record of  the POOF order in case they need it and the receiving note is  what they look at when they actually get the item to know what is going on with it, so having things like Req: there actually  helps it make more sense.
