### ISSUE TITLE
If a MARC is missing  the price or has a price we can't parse, default the price to $0

### ISSUE THREAD

**Issue by starsplatter** [cul-it/order-import-poc#41]
Set a default price of $0 so that missing price information won't keep the PO line from being created.

**Comment by fereira** [comment]
From the existing test marc files some of them have a value without "cents"  (e.g. 45 instead of 45.00).  I can normalize all price values so that they are in dollars.cents format.    I've got a fix that will return 0.00 if the data field is missing, and convert an integer value (e.g 45) to decimal (e.g. 45.00). I can prepend a $ sign to all values if desired.

**Comment by starsplatter** [comment]
I don't think we should add the dollar sign, sorry about that! The rest of this sounds great.
