### ISSUE TITLE
Update MARC field mappings

### ISSUE THREAD

**Issue by cappadona** [cul-it/order-import-poc#9]
| MARC field | Order field |
| ---------- | ----------- |
| `980$g` | quantity |
| `980$h` | fund |
| `980$v` | vendor |
| `980$y` | selector |
| `980$z` | internal note |
| `981$i` | price |
| `981$k` | currency |
| `981$n` | receiving note |
| `981$q` | if "Rush: Yes", toggle `rush` field to true |
| `981$r` | requester |

**Comment by starsplatter** [comment]
Price:
981$i

Vendor:
980$v

**Comment by starsplatter** [comment]
fund:
980$h

**Comment by fereira** [comment]
should quantity be a required field.  It's currently in 980$q

**Comment by starsplatter** [comment]
@fereira quantity should be 980$g

**Comment by starsplatter** [comment]
All the mappings for the POOF case:
980$y Selector
980$g Quantity
980$h fund
980$z - internal note
980$v - vendor

981$k currency
981$n receiving note
981$q if Rush: Yes toggle rush field to true
981$i price
981$r Requester

**Comment by cappadona** [comment]
@starsplatter Is this complete on your end, or are you still working through the non POOF case?

**Comment by fereira** [comment]
Previously a Note was in the 980$n field.   980$z was used as the Electronic Indicator.  If it’s going to be used for an Internal note I’ll need to know what field is used to indicate that item is electronic or physical



From: Jenn Colt ***@***.***>
Reply-To: cul-it/order-import-poc ***@***.***>
Date: Sunday, March 21, 2021 at 2:11 PM
To: cul-it/order-import-poc ***@***.***>
Cc: John Fereira ***@***.***>, Mention ***@***.***>
Subject: Re: [cul-it/order-import-poc] Update MARC field mappings (#9)


All the mappings for the POOF case:
980$y Selector
980$g Quantity
980$h fund
980$z - internal note
980$v - vendor

981$k currency
981$n receiving note
981$q if Rush: Yes toggle rush field to true
981$i price
981$r Requester

**Comment by fereira** [comment]
What is the non-poof case?   Will there be purchase orders using the old marc subfields still be entered?   That would be a use case that wasn't communicated to me

**Comment by starsplatter** [comment]
We won't need the old fields they are from Lehigh and aren't relevant for us.

For electronic, if the 952$b is serv,remo it is electronic

For the non-POOF case, I am still working on tracking down vendor files before we edit them. It happens through automation so I have to get them off the vendor ftp rather than our system and I'm still working on it. Implementing the POOF case will take care of a large part of what will come through the app.

**Comment by fereira** [comment]
Okay…that makes sense to use the same field as is used for the physical location.   I’ll need to make some changes In the code to test the location field rather than the electronic indicator field.   I don’t believe I’ve seen any mrc files that have serv,remo in that field yet.  The mrc files I have available seem to have some, but not all of the use cases I’ll need.   That’s what issue #14 is all about:  https://github.com/cul-it/order-import-poc/issues/14


From: Jenn Colt ***@***.***>
Reply-To: cul-it/order-import-poc ***@***.***>
Date: Tuesday, March 23, 2021 at 8:29 AM
To: cul-it/order-import-poc ***@***.***>
Cc: John Fereira ***@***.***>, Mention ***@***.***>
Subject: Re: [cul-it/order-import-poc] Update MARC field mappings (#9)


We won't need the old fields they are from Lehigh and aren't relevant for us.

For electronic, if the 952$b is serv,remo it is electronic

For the non-POOF case, I am still working on tracking down vendor files before we edit them. It happens through automation so I have to get them off the vendor ftp rather than our system and I'm still working on it. Implementing the POOF case will take care of a large part of what will come through the app.

**Comment by cappadona** [comment]
@fereira I've updated the issue description, summarizing the field mappings provided in the comments. My vote is to create a separate issue for `952$b` logic.

**Comment by fereira** [comment]
We sort of already have one in issue #6 though it indicates that the 952$b field will be used for physical holdings but didn’t say that it was also going to be used to indicate that an item is electronic or physical.
From: Nick Cappadona ***@***.***>
Reply-To: cul-it/order-import-poc ***@***.***>
Date: Tuesday, March 23, 2021 at 9:38 AM
To: cul-it/order-import-poc ***@***.***>
Cc: John Fereira ***@***.***>, Mention ***@***.***>
Subject: Re: [cul-it/order-import-poc] Update MARC field mappings (#9)


@fereira<https://github.com/fereira> I've updated the issue description, summarizing the field mappings provided in the comments. My vote is to create a separate issue for 952$b logic.

**Comment by cappadona** [comment]
@fereira Correct. Since the linked PR #16 is still open, do you prefer to handle the `952$b` logic there?

**Comment by fereira** [comment]
I think we need to determine if the app is going to be used at all for eResources, and if not create an issue which pulls out all the code which references eResources.

**Comment by fereira** [comment]
Although the app currently is hardcoding the currency field as USD, all of the test data which has the currency in 981$k subfield has two instances of the $k subfield in the 981 datafield.  As a result, the MarcReader library returns USDUSD for the currency.

**Comment by cappadona** [comment]
Yep...the currency hardcoding is listed under [areas for improvement](https://github.com/cul-it/order-import-poc#lots-of-areas-for-improvement-including) in the README. Sounds like its days are numbered 😉

**Comment by fereira** [comment]
The question that I have regarding the currency field is if there is a bug in marc4j that concatenates the values of multiple instances of a subfield, or if the marc shouldn't have multiple $k subfields in the 981 field.  Other than this issue,  I have a version of the MarcUtils class which addresses all other mappings
