### ISSUE TITLE
acquisition method no longer accepts "Purchase" as a value...must provide a UUID

### ISSUE THREAD

**Issue by fereira** [cul-it/order-import-poc#99]
When posting an order to folio the required acquisition-method value used to allow a string (Purchase) but now requires a UUID. The orders/acquisition-method api will return json containing the UUID but there isn't a method in the list with a value of "Purchase"

**Comment by starsplatter** [comment]
Hi @fereira "Purchase" is in the list but it is toward the bottom. FOLIO tends to return only 10 results by default so you might need to adjust your call to ask for more list entries?

**Comment by starsplatter** [comment]
This change is preventing us from making orders in the new version of FOLIO.

**Comment by fereira** [comment]
I have an update that fixes this. I'll push it later today

Sent via the Samsung Galaxy A71 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by starsplatter** [comment]
Thank you!!!!

**Comment by starsplatter** [comment]
Hi @fereira I reviewed and merged but when it tried to deploy there were some errors related to constants. Looking at the changes again, I think that maybe you didn't have the newest version of OrderImport.java because some of Nick's most recent changes look like they were removed. Sorry I didn't see this prior to merging, there were a lot of changes and I thought maybe it was just some refactoring. I'll let you take a look and decide what you want to do, I'm not sure if just reverting the changes and then adding yours back in is what should happen or something else.

**Comment by fereira** [comment]
I will look at it on Monday. I wasn't aware that Nick had made any changes before he left

Sent via the Samsung Galaxy A71 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by starsplatter** [comment]
Thanks @fereira ! since the code wasn't compiling I have reverted the changes on main. I also did a temporary fix of hard coding this UUID so that the people in ordering will be able to work on Monday. I also pinned us to Jetty 10 because the new Jetty seems incompatible with the app. This way you can take a look at the current state of things and not have to rush through your fixes. Thank you for your help!

**Comment by fereira** [comment]
This has been fixed with the issue-96-redux branch that was merged into main
